language: objective-c #语言种类

xcode_project: Framework/LEETheme/LEETheme.xcodeproj # 项目文件相对于.travis.yml文件的路径
    
xcode_scheme: LEETheme #你需要集成测试的scheme

script:
- xctool -project Framework/LEETheme/LEETheme.xcodeproj -scheme LEETheme build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
