language: objective-c #语言种类

xcode_project: Framework/LEETheme/LEETheme.xcodeproj # 项目文件相对于.travis.yml文件的路径
    
xcode_scheme: LEETheme #你需要集成测试的scheme

osx_image: xcode9

script:
- xcodebuild clean build -sdk iphonesimulator -project Framework/LEETheme/LEETheme.xcodeproj -scheme LEETheme CODE_SIGNING_REQUIRED=NO
